
import java.awt.Color;
import javax.swing.JFrame;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DOUGLAS CARDONA
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        bg = new javax.swing.JPanel();
        imgtxt = new javax.swing.JLabel();
        citybg = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        favicon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imgtxt.setForeground(new java.awt.Color(255, 255, 255));
        imgtxt.setText("UES FMO");
        bg.add(imgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 70, 40));

        citybg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Downloads\\tienda.png")); // NOI18N
        citybg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bg.add(citybg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 450, 310));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        favicon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        favicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\parcial1,1_files\\favicon(1).png")); // NOI18N
        favicon.setText("FMOcc");
        favicon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setText("INICIAR SESIÓN");
        title.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitBtn.setText("X");
        exitBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exitBtn.setBorderPainted(false);
        exitBtn.setFocusPainted(false);
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addComponent(favicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn)
                .addGap(13, 13, 13)
                .addComponent(favicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 120));

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userLabel.setText("USUARIO");
        userLabel.setAlignmentX(20.0F);
        userLabel.setAlignmentY(20.0F);
        userLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        bg.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        userTxt.setForeground(new java.awt.Color(204, 204, 204));
        userTxt.setText("Ingrese su nombre de usuario");
        userTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        userTxt.setName("Ingrese su nombre de usuario"); // NOI18N
        userTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTxtFocusLost(evt);
            }
        });
        bg.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 30));

        passLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passLabel.setText("CONTRASEÑA");
        passLabel.setAlignmentX(20.0F);
        passLabel.setAutoscrolls(true);
        passLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        bg.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        passTxt.setForeground(new java.awt.Color(204, 204, 204));
        passTxt.setText("00000000");
        passTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        bg.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 170, 30));
        passTxt.getAccessibleContext().setAccessibleName("");

        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 220, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 30));

        loginBtn.setBackground(new java.awt.Color(0, 51, 204));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("ENTRAR");
        loginBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        loginBtn.setBorderPainted(false);
        loginBtn.setFocusPainted(false);
        loginBtn.setHideActionText(true);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        bg.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//if(userTxt.getText().trim().equals("")){
  //         userTxt.setText("Ingrese su nombre de usuario");
   //        userTxt.setForeground(Color.gray);
   //   }
    private void userTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusLost
       if(userTxt.getText().isEmpty()){
           userTxt.setText("Ingrese su nombre de usuario");
           userTxt.setForeground(Color.gray);
       }
    }//GEN-LAST:event_userTxtFocusLost

    private void userTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFocusGained
       if(userTxt.getText().trim().equals("Ingrese su nombre de usuario")){
         userTxt.setText("");
         userTxt.setForeground(Color.gray);
      }
           
    }//GEN-LAST:event_userTxtFocusGained

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
         loginBtn.setBackground(Color.RED);
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
                loginBtn.setBackground(Color.BLUE);

    }//GEN-LAST:event_loginBtnMouseExited

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
       exitBtn.setForeground(Color.RED);
       
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        exitBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitBtnMouseExited

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        String inputUser = userTxt.getText();
        char[] passUser = passTxt.getPassword();
        JFrame f = new JFrame();
        jOptionPane1.showMessageDialog(f,"User: " + inputUser +" "+"Contraseña: "+ passUser );
    }//GEN-LAST:event_loginBtnMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel citybg;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel favicon;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imgtxt;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
